GET http://localhost:8000/products/ HTTP/1.1

###

GET http://localhost:8000/products/7/ HTTP/1.1

###

DELETE  http://localhost:8000/products/1/ HTTP/1.1

###

PUT http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTMwNzA4LCJpYXQiOjE3MzU1MzA0MDgsImp0aSI6ImM1NTE0Nzk1YTAzZDRiNGQ5MWZmYjk1OTMzYzczODFmIiwidXNlcl9pZCI6Mn0.eFMPsbc89wXWm6PZ5jV4bjk8xRX92IZT-ggNGqecMY0

{
    "name": "Vacuum Cleaner",
    "price": 30.00,
    "stock": 11,
    "description": "the best model"
}

###


POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NDY4NTI0LCJpYXQiOjE3MzU0NjgyMjQsImp0aSI6IjBkZjU4MjJlNjI5MzRkMDhiMTQ5NTA4Y2YwMjQ0ZWRiIiwidXNlcl9pZCI6Mn0.tw05jRt4id3FB99vohhT6A9Qpi-ADEpRnFh4xOpKNkM

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "the newest model"
}

###

POST  http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "ivaylo",
    "password": "ivaylo"
}

###

POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MjIzNDIxLCJpYXQiOjE3MzYyMjMxMjEsImp0aSI6IjRmMjgyODVmMzQwMTRiOTBiZWQ2M2IyNjU3NzgzY2Y2IiwidXNlcl9pZCI6Mn0.t-AmRkTSryOmCiwIL0XwFB3urmRO5MYV1tdl7z0aZmU

{
            "status": "Pending",
            "items": [
                {
                    "product": 3,
                    "quantity": 1
                }
            ]
}


###

PUT http://localhost:8000/orders/6e0c6228-908f-4eea-8a82-7f5f087a3a65/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MjI0NjE0LCJpYXQiOjE3MzYyMjQzMTQsImp0aSI6IjdmZTYzNTRjNDE2YTRiZTY4MGNmZmNmYWUyZjM5YmM2IiwidXNlcl9pZCI6Mn0.PXv100Y64meWzuso1WkRjSV0xBLRt1cRpwEF1t2b_nI

{
    "status": "Confirmed"
}

###

DELETE http://localhost:8000/orders/6e0c6228-908f-4eea-8a82-7f5f087a3a65/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MjI1MTExLCJpYXQiOjE3MzYyMjQ4MTEsImp0aSI6ImRhZTY0ODgzZWNjOTQ0ZjM5YzBiNzRmMTk2NGQwMWIzIiwidXNlcl9pZCI6Mn0.svML9brLZJ1XiNp9qO7wkkQWmpy0_57qOPu5kpBchUQ


###

GET http://localhost:8000/orders/6e0c6228-908f-4eea-8a82-7f5f087a3a65/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MjI1MTExLCJpYXQiOjE3MzYyMjQ4MTEsImp0aSI6ImRhZTY0ODgzZWNjOTQ0ZjM5YzBiNzRmMTk2NGQwMWIzIiwidXNlcl9pZCI6Mn0.svML9brLZJ1XiNp9qO7wkkQWmpy0_57qOPu5kpBchUQ
